# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenMapMatMult <- function(A, B) {
    .Call('_staggered_eigenMapMatMult', PACKAGE = 'staggered', A, B)
}

solve_least_squares_svd <- function(A, B) {
    .Call('_staggered_solve_least_squares_svd', PACKAGE = 'staggered', A, B)
}

solve_least_squares_normal <- function(A, B) {
    .Call('_staggered_solve_least_squares_normal', PACKAGE = 'staggered', A, B)
}

